services:
  - type: web
    name: nafsketch-app
    env: python
    plan: starter  # Use paid plan for more memory
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 1 --max-requests 100 --max-requests-jitter 10 --preload
    envVars:
      - key: EMAIL_SENDER
        value: nafisabdullah424@gmail.com
      - key: EMAIL_PASSWORD
        value: zeqv zybs klyg qavn
      - key: EMAIL_RECIPIENT
        value: nafisabdullah424@gmail.com
